spring:
  application:
    name: maas-wallet
  profiles:
    active: dev

  jackson:
    date-format: yyyy-MM-dd'T'HH:mm:ss'Z'
    time-zone: UTC
    serialization:
      write-dates-as-timestamps: false

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: method

# Configurações de Negócio Customizadas da Aplicação
app:
  security:
    jwt:
      secret: "maas-wallet-super-secret-key-for-jwt-signing-2026-06-14-token-signature"
      expiration-ms: 86400000 # 24 horas
  recharge:
    max-limit: 10000.00
    min-limit: 1.00
